name: glenglat

channels:
  - conda-forge

dependencies:
  - python=3.9
  - frictionless=5.13
  - pandas=2.2
  - pytest=7.3
  - markdown=3.4
  - pip=24.0
  - pip:
    - 'tablecloth[excel,gsheets] @ git+https://github.com/ezwelty/tablecloth'
