name: glenglat

channels:
  - conda-forge

dependencies:
  - python=3.9
  - frictionless=5.13
  - pandas=2.2
  - pytest=7.3
  - markdown=3.4
  - python-dotenv=0.21
  - requests=2.32
  - fire=0.6
  - gitpython=3.1
  - pip=24.0
  - xlsxwriter=3.2
  - pip:
    - 'tablecloth[excel,gsheets] @ git+https://github.com/ezwelty/tablecloth@v0.1.0'
